version: "3"

services:
  node:
    image: node:14
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: "yarn dev"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senhafortedemaismds"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

networks:
  postgres-node:
    driver: bridge

volumes:
  dbdata:
