version: "3"

services:
  node:
    build: .
    container_name: node
    ports:
      - "${PORT}:${PORT}"
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    volumes:
      - ./:/app
    working_dir: /app
    command: "yarn dev"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}?schema=public"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  postgres:
