version: "3"

services:
  node:
    image: node:14
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}?schema=public"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    working_dir: /app
    command: "yarn dev"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
